<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="17.1060" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2022-01-13T06:43:35" tests="0" file="cypress/integration/code/checkingLoginPage.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Basic tests" timestamp="2022-01-13T06:43:35" tests="2" time="17.0910" failures="2">
    <testcase name="Basic tests go to site" time="0.0000" classname="go to site">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It&apos;s possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

https://on.cypress.io/cross-origin-script-error" type="Error"><![CDATA[Error: The following error originated from your application code, not from Cypress.

  > Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

https://on.cypress.io/cross-origin-script-error
]]></failure>
    </testcase>
    <testcase name="Basic tests We have correct page title" time="0.0000" classname="We have correct page title">
      <failure message="Timed out retrying after 4050ms: `cy.click()` failed because this element is not visible:

`&lt;a class=&quot;border-white text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium sm:pl-5 sm:pr-6&quot; href=&quot;/login&quot;&gt;Sign in&lt;/a&gt;`

This element `&lt;a.border-white.text-gray-500.hover:bg-gray-50.hover:border-gray-300.hover:text-gray-700.block.pl-3.pr-4.py-2.border-l-4.text-base.font-medium.sm:pl-5.sm:pr-6&gt;` is not visible because its parent `&lt;div#mobile-menu.shadow-inner.lg:hidden.hidden&gt;` has CSS property: `display: none`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with" type="CypressError"><![CDATA[CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is not visible:

`<a class="border-white text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium sm:pl-5 sm:pr-6" href="/login">Sign in</a>`

This element `<a.border-white.text-gray-500.hover:bg-gray-50.hover:border-gray-300.hover:text-gray-700.block.pl-3.pr-4.py-2.border-l-4.text-base.font-medium.sm:pl-5.sm:pr-6>` is not visible because its parent `<div#mobile-menu.shadow-inner.lg:hidden.hidden>` has CSS property: `display: none`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
    at runVisibilityCheck (https://codedamn.com/__cypress/runner/cypress_runner.js:162635:76)
    at $Cy.ensureStrictVisibility (https://codedamn.com/__cypress/runner/cypress_runner.js:162651:12)
    at runAllChecks (https://codedamn.com/__cypress/runner/cypress_runner.js:149890:14)
    at retryActionability (https://codedamn.com/__cypress/runner/cypress_runner.js:149945:16)
    at tryCatcher (https://codedamn.com/__cypress/runner/cypress_runner.js:13196:23)
    at Function.Promise.attempt.Promise.try (https://codedamn.com/__cypress/runner/cypress_runner.js:10470:29)
    at whenStable (https://codedamn.com/__cypress/runner/cypress_runner.js:167470:63)
    at https://codedamn.com/__cypress/runner/cypress_runner.js:166968:14
    at tryCatcher (https://codedamn.com/__cypress/runner/cypress_runner.js:13196:23)
    at Promise._settlePromiseFromHandler (https://codedamn.com/__cypress/runner/cypress_runner.js:11131:31)
    at Promise._settlePromise (https://codedamn.com/__cypress/runner/cypress_runner.js:11188:18)
    at Promise._settlePromise0 (https://codedamn.com/__cypress/runner/cypress_runner.js:11233:10)
    at Promise._settlePromises (https://codedamn.com/__cypress/runner/cypress_runner.js:11313:18)
    at Promise._fulfill (https://codedamn.com/__cypress/runner/cypress_runner.js:11257:18)
    at https://codedamn.com/__cypress/runner/cypress_runner.js:12871:46
From Your Spec Code:
    at Context.eval (https://codedamn.com/__cypress/tests?p=cypress\integration\code\checkingLoginPage.js:108:28)]]></failure>
    </testcase>
  </testsuite>
</testsuites>